version: "3.8"
services:
  fallback_monitor:
    container_name: fallback_monitor
    build:
      context: .
      dockerfile: Dockerfile
      target: fallback_monitor
    restart: unless-stopped
    networks:
      - net
    env_file:
      - ./fallback_monitor/.env

  turbo-da-core:
    container_name: turbo-da-core
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: Dockerfile
      target: turbo-da-core
    restart: unless-stopped
    networks:
      - net
    volumes:
      - ./turbo-da-core/whitelist.json:/whitelist.json
      - ./turbo-da-core/public_key.pem:/public_key.pem
    env_file:
      - ./turbo-da-core/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: "redis:alpine"
    command: redis-server --save "" --appendonly no 
    networks:
      - net
    ports:
      - 6379:6379

networks:
  net:
    driver: bridge
