version: "3.8"
services:
  otc:
    image: otel/opentelemetry-collector-contrib:0.89.0
    container_name: otc
    volumes:
      - ./observability/config/otel-collector-config.yaml:/etc/otelcol/config.yaml
    command: --config /etc/otelcol/config.yaml
    env_file:
      - ./observability/config/.env
    ports:
      - 1888:1888 
      - 8888:8888 
      - 8889:8889 
      - 13133:13133 
      - 4317:4317 
      - 4318:4318
      - 55679:55679 
    networks:
      - net
networks:
  net:
    external: true
