version: "3.8"
services:
  redis:
    image: "redis:alpine"
    command: redis-server --save "" --appendonly no
    networks:
      - net
    ports:
      - 6379:6379
  fallback_monitor:
    container_name: fallback_monitor
    build:
      context: .
      dockerfile: Dockerfile
      target: fallback_monitor
    restart: unless-stopped
    networks:
      - net
    env_file:
      - ./fallback_monitor/.env

  turbo-da-core:
    container_name: turbo-da-core
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: Dockerfile
      target: turbo-da-core
    restart: unless-stopped
    networks:
      - net
    env_file:
      - ./turbo-da-core/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  data_submission:
    container_name: data_submission
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile
      target: data_submission
    restart: unless-stopped
    networks:
      - net
    env_file:
      - ./data_submission/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  net:
    name: turboda-net
    driver: bridge
