version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=unaruto123
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  migration:
    container_name: migration
    image: rust:latest
    volumes:
      - ./db:/scripts
    entrypoint: bash -c "apt update && apt install -y jq && cd scripts && chmod +x /scripts/migration.sh && /scripts/migration.sh"

volumes:
  postgres_data:
  redis_data: