CREATE TABLE accounts ( 
    id UUID UNIQUE PRIMARY KEY,
    user_id VARCHAR NOT NULL,
    app_id INTEGER NOT NULL,
    credit_balance NUMERIC(39, 0) NOT NULL DEFAULT 0,
    credit_used NUMERIC(39, 0) NOT NULL DEFAULT 0,
    fallback_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);



