[package]
name = "fallback_monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel.workspace = true
bigdecimal.workspace = true
dotenv.workspace = true
serde.workspace = true
serde_json.workspace = true
log.workspace = true
env_logger.workspace = true
uuid.workspace = true
tokio.workspace = true
chrono = { version = "0.4", features=["serde"] }
lazy_static = "1.4"
diesel-async.workspace = true
futures.workspace = true
cron = { version = "0.8" }
toml.workspace = true
avail-rust = { workspace = true }
db = {path = "../db" }
reqwest = "0.12.9"
avail-utils = {path = "../avail"}
observability = { path = "../observability" }
turbo-da-core = {path= "../turbo-da-core"}
enigma = {path="../enigma"}
data_submission = {path = "../data_submission"}
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-opentelemetry = { workspace = true }
