[package]
name = "db"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel.workspace = true
bigdecimal.workspace = true
chrono = { version = "0.4", features=["serde"] }
serde.workspace = true
uuid.workspace = true
dotenv.workspace = true
diesel-async.workspace = true
log.workspace = true
serde_json.workspace = true
avail-utils = { path = "../avail"}
enigma = { path = "../enigma" }
