name: Mainnet Deployment

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  deploy-vm2:
    runs-on: ubuntu-latest
    steps:
      - name: Health check VM1
        run: |
          VM1_HEALTH=$(curl -s -o /dev/null -w "%{http_code}" http://${{ secrets.VM1_IP }}:8000/health || echo "failed")
          
          if [[ "$VM1_HEALTH" != "200" ]]; then
            echo "VM1 is not healthy. Cannot proceed with rolling deployment."
            exit 1
          fi

      - name: Deploy to VM2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM2_IP }}
          username: root
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            set -e
            REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
            REPO_URL="${{ github.server_url }}/${{ github.repository }}.git"
            BRANCH="${{ github.event.inputs.branch }}"
            
            mkdir -p /opt/turbo-deploy
            cd /opt/turbo-deploy
            
            # Clone/pull latest code
            if [ -d "$REPO_NAME" ]; then
              cd $REPO_NAME
              git fetch
              git checkout $BRANCH
              git pull origin $BRANCH
            else
              git clone -b $BRANCH $REPO_URL $REPO_NAME
              cd $REPO_NAME
            fi
            
            echo '${{ secrets.WHITELIST_JSON }}' > whitelist.json
            
            # Remove fallback_monitor service as this is VM2
            yq eval 'del(.services.fallback_monitor)' docker-compose.yaml > docker-compose.tmp.yaml
            mv docker-compose.tmp.yaml docker-compose.yaml
            
            docker compose build --no-cache
            docker compose up -d
            docker image prune -f
            
            # Wait for service to be healthy
            for i in {1..30}; do
              if curl -s http://localhost:8000/health | grep -q "ok"; then
                echo "Service is healthy"
                exit 0
              fi
              echo "Waiting for service to become healthy... attempt $i"
              sleep 10
            done
            echo "Service failed to become healthy"
            exit 1

  deploy-vm1:
    needs: deploy-vm2
    runs-on: ubuntu-latest
    steps:
      - name: Health check VM2
        run: |
          VM2_HEALTH=$(curl -s -o /dev/null -w "%{http_code}" http://${{ secrets.VM2_IP }}:8000/health || echo "failed")
          
          if [[ "$VM2_HEALTH" != "200" ]]; then
            echo "VM2 is not healthy. Cannot proceed with rolling deployment."
            exit 1
          fi

      - name: Deploy to VM1
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM1_IP }}
          username: root
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            set -e
            REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
            REPO_URL="${{ github.server_url }}/${{ github.repository }}.git"
            BRANCH="${{ github.event.inputs.branch }}"
            
            mkdir -p /opt/turbo-deploy
            cd /opt/turbo-deploy
            
            # Clone/pull latest code
            if [ -d "$REPO_NAME" ]; then
              cd $REPO_NAME
              git fetch
              git checkout $BRANCH
              git pull origin $BRANCH
            else
              git clone -b $BRANCH $REPO_URL $REPO_NAME
              cd $REPO_NAME
            fi
            
            echo '${{ secrets.WHITELIST_JSON }}' > whitelist.json
            
            docker compose build --no-cache
            docker compose up -d
            docker image prune -f
            
            # Wait for service to be healthy
            for i in {1..30}; do
              if curl -s http://localhost:8000/health | grep -q "ok"; then
                echo "Service is healthy"
                exit 0
              fi
              echo "Waiting for service to become healthy... attempt $i"
              sleep 10
            done
            echo "Service failed to become healthy"
            exit 1

  verify-deployment:
    needs: deploy-vm1
    runs-on: ubuntu-latest
    steps:
      - name: Verify all services are healthy
        run: |
          VM1_HEALTH=$(curl -s -o /dev/null -w "%{http_code}" http://${{ secrets.VM1_IP }}:8000/health || echo "failed")
          VM2_HEALTH=$(curl -s -o /dev/null -w "%{http_code}" http://${{ secrets.VM2_IP }}:8000/health || echo "failed")
          
          if [[ "$VM1_HEALTH" != "200" ]] || [[ "$VM2_HEALTH" != "200" ]]; then
            echo "Not all services are healthy after deployment"
            echo "VM1 Health: $VM1_HEALTH"
            echo "VM2 Health: $VM2_HEALTH"
            exit 1
          fi
          echo "All services are healthy"










